name: Generate pacman animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman-contribution-graph.svg (dark mode)
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          # PERSONALIZAÇÃO:
          background_color: "#0d1117"   # fundo escuro
          grid_color: "#30363d"         # cor das "paredes"
          pacman_color: "#fbd405"       # amarelo do pacman
          ghost_color: "#ff007f"        # rosa/roxo das fantasminhas
          dot_color: "#ffffff"          # bolinhas
          outline_color: "#000000"      # contorno

      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
